server:
  port: 8082

spring:
  application:
    name: notification-service

resilience4j:
  circuitbreaker:
    instances:
      mail:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 2
        recordExceptions:
          - org.springframework.mail.MailException
          - java.net.SocketTimeoutException
          - java.io.IOException

  retry:
    instances:
      mail:
        maxAttempts: 2
        waitDuration: 200ms
        retryExceptions:
          - org.springframework.mail.MailException
          - java.net.SocketTimeoutException
          - java.io.IOException
